### ISSUE TITLE
[BUG][High] Bug linked to mk_create_tables.sql (incorrect modifications)

### ISSUE THREAD

**Issue by Petrus3D** [Herklos/Monark2#5]
Les modèles ont été modifiés et ne correspondent plus aux tables (de départ).
Est-il possible de disposer d'un nouveau fichier **mk_create_tables.sql**, afin de pouvoir mettre à jour la base de données ?

**Comment by Herklos** [comment]
Je n'ai pas modifié de tables. Quel model à été modifié ?

**Comment by Herklos** [comment]
mk_create_table.sql mis à jour.

**Comment by Petrus3D** [comment]
J'ai supprimé toutes les tables et ré-injecter le fichier "mk_create_tables.sql"
cependant il y a des champs qui n'existent pas.
Par exemple le champ "**game_map_cont**" de la table "game" est utilisé lors de la création d'une partie. Voici la requete concernée : 

INSERT INTO `game` (`game_name`, `game_pwd`, `game_owner_id`, `game_max_player`, `game_create_time`, `game_statut`, `game_map_id`, `game_map_cont`, `game_mod_id`, `game_turn_time`, `game_difficulty_id`, `game_won_user_id`, `game_won_time`, `game_key`) VALUES ('8QOMel1XjvO1U7A3E1TEcAoe3tRyHpBBExN4YqjUqS8=', 'EQ23wFWC0rjxrt4oFsWCchuSccngXEjgtc6gxZdhHSebIERHjY1GTkWJL/+xIq2/oJKjPnz13SNbuJLjCtXJbUh01AZVlfKmpG3LM/aG/kzQJdsDetcPDopyGDUzD+xX|Akoy4FJzI2UMc49cJHuD+BRF6THAsTqchdti6bFQLxM=', 273, 2, 1469567070, 0, 1, 0, 0, 0, 0, 0, 0, '0');

Le champ "**game_map_cont**"  n'est pas présent dans le fichier "**mk_create_tables.sql**" du 26/07/2016.

**Comment by Herklos** [comment]
Tout à fait, je n'avais pas encore rencontré ce problème. Merci.
Corrigé sur le [Commit](https://github.com/Herklos/Monark2/commit/0d7e8b90f0e7ef7f535cf3aa52fd2c6741a5ecf8).
Désolé.

**Comment by Herklos** [comment]
Risque identifié : la nouvelle colonne game_map_cont doit être remplie avec 1 si c'est une carte avec des continents (comme la carte du monde) et 0 si elle n'en possède pas comme la carte des USA. Par défaut en créant la colonne tout sera à 1. Il va falloir modifié en cas de pb.

**Comment by Petrus3D** [comment]
Le dernier fichier mk_create_tables.sql" fonctionne bien !
Merci.
